ARG PYTORCH_VERSION="1.13.1"
ARG CUDA_VERSION="11.6"
ARG cuDNN_VERSION="8"
ARG Flavor="runtime"

# Specify image
FROM pytorch/pytorch:${PYTORCH_VERSION}-cuda${CUDA_VERSION}-cudnn${cuDNN_VERSION}-${Flavor}

# Ensure apt is in non-interactive to avoid prompts
ENV DEBIAN_FRONTEND=noninteractive
# Set TimeZone to KST
ENV TZ=Asia/Seoul

# Set working directory
WORKDIR /project
# Copy requirements
COPY ../requirements.txt /project/

# Expose port 80
EXPOSE 80

# Install dependencies
RUN \
    apt-get update && apt-get upgrade -y &&\
    apt-get install wget curl git vim imagemagick tzdata zsh fonts-powerline -y

# Setup ZSH(Z Shell)
RUN \
    chsh -s /bin/zsh &&\
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" &&\
    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions &&\
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting &&\
    perl -pi -w -e 's/ZSH_THEME=.*/ZSH_THEME="agnoster"/g;' ~/.zshrc &&\
    perl -pi -w -e 's/plugins=.*/plugins=(git ssh-agent zsh-autosuggestions zsh-syntax-highlighting)/g;' ~/.zshrc

# Prevent TimeZone mismatch error
RUN apt-get install language-pack-en -y && update-locale



# Install requirements
RUN conda activate base && pip install -r requirements.txt
# RUN pip install --use-deprecated=legacy-resolver -r requirements.txt

# Cleanup Cache files
RUN \
    apt-get clean &&\
    apt-get autoclean &&\
    apt-get autoremove -y &&\
    rm -rf /var/lib/cache/* &&\
    rm -rf /var/lib/log/*