version: "3.7" # docker-compose version number

services:
  main:
    container_name: neuralop
    env_file:
      - ../.env
    build:
      # build image from dockerfile
      context: .. # Set current working directory
      dockerfile: .devcontainer/Dockerfile
    image: pytorch-jax:jax0.4.11-torch2.0.0-cuda12.1-cudnn8.9 # image name + tag
    ipc: host # --ipc host, use shared memory
    ports:
      - "9090:22" 
      - "9091:80"
    volumes:
      # mount directory
      - ..:/project
    tty: true # -it
    deploy: # --gpus all
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    entrypoint: ["/bin/zsh", "-c"]
    command:
      - |
        git config --global user.name $${git_username}
        git config --global user.email $${git_useremail}
        sleep infinity
